addons:
  postgresql: 9.6
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database task_app_test;' -U postgres
dist: centos/7
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec